name: CI
-name: Cache
uses: actions/cache@v1.0.3
  with:
    # A directory to store and save the cache
    path: 
    # An explicit key for restoring and saving the cache
    key: 
    # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
    restore-keys: # optional
on: [push]
- name: Upload artifact
  uses: actions/upload-artifact@v1.0.0
  with:
    # Artifact name
    name: 
    # Directory containing files to upload
    path: 
jobs:
  build:
- name: Setup Go for use with actions
  uses: actions/setup-go@v1.0.0
  with:
    # The Go version to download (if necessary) and use. Example: 1.9.3
    version: # optional, default is 1.10
    runs-on: ubuntu-latest
- name: GitHub Action for Firebase
  uses: w9jds/firebase-action@v1.1.0
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        - name: Setup Java Action
  uses: actions/setup-java@v1.0.0
  with:
    # The JDK version to make available on the path. Takes a whole or semver Jdk version, or 1.x syntax (e.g. 1.8 => Jdk 8.x)
    version: 
    # The architecture (x86, x64) of the JDK.
    architecture: # default is x64
    # Path to where the compressed JDK is located. The path could be in your source repository or a local path on the agent.
    jdkFile: # optional 
         echo Add other actions to build,
        echo test, and deploy your project.
